baseurl      = "https://kyansystems.com"
title        = "Kyan Systems"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Rethinking Fundamentals"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Kyan Systems"
  keywords = ""
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Kyan Systems"
    subtitle = "Rethinking Fundamentals"
    keywords = ""
    copyright = "" 
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "opal play"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "/About"

    [[params.social]]
      name = "github"
      url = "https://github.com/kyansystems"

